---
name: Data-Pond
version: 0.000
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: Perl-based open notation for data
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  Params::Classify: 0
  parent: 0
  perl: 5.008
  strict: 0
  warnings: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.008
  strict: 0
  warnings: 0
recommends:
  XSLoader: 0
dynamic_config: 1
provides:
  Data::Pond:
    file: lib/Data/Pond.pm
    version: 0.000
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
